languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Golang Book"
logo = "img/Go-Logo_Blue.png"
description = "This blog will take you from zero to hero in Golang."
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = ":date_medium"

[author]
  name = "Mohamed Allam"
  image = "img/mohamedallam.jpg"
  headline = "Cant get my hands off the keyboard"
  bio = "Self taught web developer, data structure algorithms, Golang system programming, performance, databases is what fuels me the most"
  links = [
    { email = "mailto:meda3gm@gmail.com/" },
    { link = "https://mohamedallam.pages.dev/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/mohamedallam1991/" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
    { hashnode = "https://mohamedallam.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
    { mastodon = "https://mastodon.technology/@mohamed" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
    { telegram = "https://t.me/mohamedallamTech" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://youtube.com/username" },
  ]
